### ISSUE TITLE
document methods how to access VA

### ISSUE THREAD

**Issue by semik** [OmniTrustILM/documentation#112]

**Comment by 3keyroman** [comment]
@semik , can you please provide more details about this issue?

**Comment by semik** [comment]
@3keyroman, I've seen some of our clients using console of virtual machine, which I find quite painful. So I made this issue as a reminder for me to implement that also SSH is available. 

Now I'm checking documentation and I see that info about SSH already there. See second paragraph on page https://docs.czertainly.com/docs/certificate-key/installation-guide/deployment/deployment-appliance/initialization At this moment do not see what to add into documentation.

Do you have any idea how to improve this? If you do, please reopen this issue. 

Sorry for leaving this open for so long.
