### ISSUE TITLE
Structure of documentation

### ISSUE THREAD

**Issue by semik** [OmniTrustILM/documentation#64]
Installation Guide is hidden inside of "Certificates and Cryptographic Keys". It has used to be in root of documentation tree, actual placement looks quite confusing to me.

**Comment by 3keyroman** [comment]
Documentation will be consolidated after merging all parts of CZERTAINLY signing. Currently installation guide differs for signatures, and for certificates/cryptographic keys. That is the reason, why it is inside "Certificates and Cryptographic Keys".
